### PR TITLE
Xdebug 2.3.2

### PR DESCRIPTION
**Pull request by mlocher**
This includes the changes from #265 as well, but adds a commit to update to the latest version of Xdebug.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We need to update ALL definitions (that support it) to the new xdebug.

**Comment by mlocher** [comment]
Yeah, I accidentally created the PR on the wrong repository :( I'll push a new commit with updated definitions for all versions that support 2.3.2 once I have a spare minute!

**Comment by GrahamCampbell** [comment]
This needs rebasing and squashing.

**Comment by rogeriopradoj** [comment]
@GrahamCampbell can we merge this right now?

**Comment by GrahamCampbell** [comment]
One sec. I'll rebase it...

**Comment by GrahamCampbell** [comment]
Employing some clever git stuff...

**Comment by GrahamCampbell** [comment]
@rogeriopradoj #267.

**Pull request closed without merging**
