### PR TITLE
Updated to xdebug 2.3.1

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by stof** [comment]
The Xdebug 2.3 setup does not seem to work. The Travis build is failing for definitions using it

**Comment by GrahamCampbell** [comment]
:

**Comment by GrahamCampbell** [comment]
:(

**Comment by stof** [comment]
@GrahamCampbell before debugging the issue, it might be worth switching to 2.3.1 already

**Comment by GrahamCampbell** [comment]
Pushed.

**Comment by stof** [comment]
looks like the Travis build has not been triggered. This is weird

**Comment by stof** [comment]
the reason is http://www.traviscistatus.com/incidents/bc3jgcrjs7gt

**Comment by stof** [comment]
and it looks like the update to Xdebug 2.3.1 fixed the compilation

**Comment by rogeriopradoj** [comment]
@stof do you think the merge now will work fine?

/cc @GrahamCampbell (could you rebase the PR, please? there are conflicts now with master. Thanks!)

**Comment by stof** [comment]
The conflict is only because you merged another PR removing the definitions for 5.6-beta versions

**Comment by rogeriopradoj** [comment]
I am right now a merge machine, but in a mobile phone only :-( (because of [#mbp2011](mbp2011.org) .

Please, as soon as it is rebased, we merge! 



—
Rogerio

**Comment by GrahamCampbell** [comment]
> The conflict is only because you merged another PR removing the definitions for 5.6-beta versions

I'll still need to update this in order to have the new definitions i added update too.

**Comment by GrahamCampbell** [comment]
Rebased and updated. Let's see what travis makes of it...

**Comment by GrahamCampbell** [comment]
Ping @rogeriopradoj. Travis is green btw. :)

**Comment by rogeriopradoj** [comment]
Thanks, @GrahamCampbell !

**Comment by GrahamCampbell** [comment]
Any time. :)

**Pull request merged**
