### PR TITLE
Added php 5.4.27, 5.5.21, and 5.6.5

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This adds definitions for the very latest php releases.

### CODE REVIEW

**Comment by rogeriopradoj** [comment]
Thanks, @GrahamCampbell! I just removed 5.4.37 because its released yet, ok?

https://travis-ci.org/CHH/php-build/jobs/47960991#1-1644

See ya!

**Comment by GrahamCampbell** [comment]
@rogeriopradoj it gets released today. I sent this pull request in preparation for that release, like I've done in the past. I wasn't expecting it to be merged yet.

**Comment by rogeriopradoj** [comment]
:-) Could you send it again? Sorry for this...

**Comment by GrahamCampbell** [comment]
Done. #254.

**Pull request merged**
