### PR TITLE
Remove Xdebug in the PHP master definition as it does not support PHP7

### PR DESCRIPTION
**Pull request by stof**
See the discussion in https://github.com/travis-ci/travis-ci/issues/2480#issuecomment-74901214

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by stof** [comment]
@rogeriopradoj @loicfrering any change needed here ?

**Comment by rogeriopradoj** [comment]
@stof, I think it's ok for merge. The link you provided cites Travis. @loicfrering , any thoughts about it?

**Comment by rogeriopradoj** [comment]
Merged, thanks, @stof!

**Pull request merged**
