### PR TITLE
Updated to include the latest php releases

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Ping @rogeriopradoj, @loicfrering.

**Comment by stof** [comment]
:+1:

**Comment by chadrien** [comment]
:+1:

**Comment by nishimaki10** [comment]
:+1:

**Comment by troter** [comment]
:+1:

**Comment by felipecwb** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Ping @rogeriopradoj, @loicfrering.

**Comment by rogeriopradoj** [comment]
Sorry everyone! Our bad! (I going to get married this weekend, going a little crazy :-) ) See ya!

**Comment by GrahamCampbell** [comment]
> I going to get married this weekend

Congratulations!

**Comment by felipecwb** [comment]
congrats @rogeriopradoj

**Pull request merged**
